In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)

clvar_df = pd.read_csv(
    "../../resources/variant_summary.txt.gz",
    sep="\t",
    compression="gzip",
)
clvar_df

/var/folders/57/yk3w62md44z9m6ndy61mkkz80000gn/T/ipykernel_2566/2249912466.py:5: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  clvar_df = pd.read_csv(

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),nsv/esv (dbVar),RCVaccession,PhenotypeIDS,PhenotypeList,Origin,OriginSimple,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele,Cytogenetic,ReviewStatus,NumberSubmitters,Guidelines,TestedInGTR,OtherIDs,SubmitterCategories,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh37,NC_000007.13,7,4820844,4820847,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4820844,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh38,NC_000007.14,7,4781213,4781216,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4781213,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh37,NC_000007.13,7,4827361,4827374,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4827360,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh38,NC_000007.14,7,4787730,4787743,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4787729,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,-,RCV000000014,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,germline,germline,GRCh37,NC_000015.9,15,85342440,85342440,na,na,15q25.3,no assertion criteria provided,1,-,N,"ClinGen:CA210674,UniProtKB:Q92610#VAR_064583,O...",1,4,85342440,G,A,-,-,-,-,-,-,SCV000020157,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8982604,4963058,single nucleotide variant,NM_001355436.2(SPTB):c.251A>T (p.Asp84Val),6710,SPTB,HGNC:11274,Likely pathogenic,1,"Apr 21, 2026",-1,-,RCV006699155,"MONDO:MONDO:0000913,MedGen:C2674219,OMIM:61664...",Hereditary spherocytosis type 2,germline,germline,GRCh38,NC_000014.9,14,64804988,64804988,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852113,64804988,T,A,-,-,-,-,-,-,SCV007541406,-,-
8982605,4963059,single nucleotide variant,NM_058172.6(ANTXR2):c.236G>T (p.Arg79Ile),118429,ANTXR2,HGNC:21732,Likely pathogenic,1,"Apr 21, 2026",-1,-,RCV006699156,"MONDO:MONDO:0009229,MedGen:C5574677,OMIM:22860...",Hyaline fibromatosis syndrome,germline,germline,GRCh37,NC_000004.11,4,80990650,80990650,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852114,80990650,C,A,-,-,-,-,-,-,SCV007541397,-,-
8982606,4963059,single nucleotide variant,NM_058172.6(ANTXR2):c.236G>T (p.Arg79Ile),118429,ANTXR2,HGNC:21732,Likely pathogenic,1,"Apr 21, 2026",-1,-,RCV006699156,"MONDO:MONDO:0009229,MedGen:C5574677,OMIM:22860...",Hyaline fibromatosis syndrome,germline,germline,GRCh38,NC_000004.12,4,80069496,80069496,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852114,80069496,C,A,-,-,-,-,-,-,SCV007541397,-,-
8982607,4963060,single nucleotide variant,NM_004519.4(KCNQ3):c.1969T>C (p.Tyr657His),3786,KCNQ3,HGNC:6297,Likely benign,0,"Apr 27, 2026",-1,-,RCV006699157,"MONDO:MONDO:0007366,MedGen:C1852581,OMIM:12120...","Seizures, benign familial neonatal, 2",germline,germline,GRCh37,NC_000008.10,8,133142159,133142159,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852115,133142159,A,G,-,-,-,-,-,-,SCV007579320,-,-
8982608,4963060,single nucleotide variant,NM_004519.4(KCNQ3):c.1969T>C (p.Tyr657His),3786,KCNQ3,HGNC:6297,Likely benign,0,"Apr 27, 2026",-1,-,RCV006699157,"MONDO:MONDO:0007366,MedGen:C1852581,OMIM:12120...","Seizures, benign familial neonatal, 2",germline,germline,GRCh38,NC_000008.11,8,132129912,132129912,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852115,132129912,A,G,-,-,-,-,-,-,SCV007579320,-,-

In [3]:
clvar_df["Name"] = clvar_df["GeneSymbol"] + ":" + clvar_df["Name"].str.split(":", n=1).str[1]
clvar_df["Name"] = clvar_df["Name"].str.replace(r"[()]", "", regex=True)

clvar_df

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),nsv/esv (dbVar),RCVaccession,PhenotypeIDS,PhenotypeList,Origin,OriginSimple,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele,Cytogenetic,ReviewStatus,NumberSubmitters,Guidelines,TestedInGTR,OtherIDs,SubmitterCategories,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,AP5Z1:c.80_83delinsTGCTGTAAACTGTAACTGTAAA p.Ar...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh37,NC_000007.13,7,4820844,4820847,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4820844,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,AP5Z1:c.80_83delinsTGCTGTAAACTGTAACTGTAAA p.Ar...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh38,NC_000007.14,7,4781213,4781216,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4781213,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,AP5Z1:c.1413_1426del p.Leu473fs,9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh37,NC_000007.13,7,4827361,4827374,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4827360,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,AP5Z1:c.1413_1426del p.Leu473fs,9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh38,NC_000007.14,7,4787730,4787743,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4787729,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,ZNF592:c.3136G>A p.Gly1046Arg,9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,-,RCV000000014,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,germline,germline,GRCh37,NC_000015.9,15,85342440,85342440,na,na,15q25.3,no assertion criteria provided,1,-,N,"ClinGen:CA210674,UniProtKB:Q92610#VAR_064583,O...",1,4,85342440,G,A,-,-,-,-,-,-,SCV000020157,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8982604,4963058,single nucleotide variant,SPTB:c.251A>T p.Asp84Val,6710,SPTB,HGNC:11274,Likely pathogenic,1,"Apr 21, 2026",-1,-,RCV006699155,"MONDO:MONDO:0000913,MedGen:C2674219,OMIM:61664...",Hereditary spherocytosis type 2,germline,germline,GRCh38,NC_000014.9,14,64804988,64804988,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852113,64804988,T,A,-,-,-,-,-,-,SCV007541406,-,-
8982605,4963059,single nucleotide variant,ANTXR2:c.236G>T p.Arg79Ile,118429,ANTXR2,HGNC:21732,Likely pathogenic,1,"Apr 21, 2026",-1,-,RCV006699156,"MONDO:MONDO:0009229,MedGen:C5574677,OMIM:22860...",Hyaline fibromatosis syndrome,germline,germline,GRCh37,NC_000004.11,4,80990650,80990650,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852114,80990650,C,A,-,-,-,-,-,-,SCV007541397,-,-
8982606,4963059,single nucleotide variant,ANTXR2:c.236G>T p.Arg79Ile,118429,ANTXR2,HGNC:21732,Likely pathogenic,1,"Apr 21, 2026",-1,-,RCV006699156,"MONDO:MONDO:0009229,MedGen:C5574677,OMIM:22860...",Hyaline fibromatosis syndrome,germline,germline,GRCh38,NC_000004.12,4,80069496,80069496,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852114,80069496,C,A,-,-,-,-,-,-,SCV007541397,-,-
8982607,4963060,single nucleotide variant,KCNQ3:c.1969T>C p.Tyr657His,3786,KCNQ3,HGNC:6297,Likely benign,0,"Apr 27, 2026",-1,-,RCV006699157,"MONDO:MONDO:0007366,MedGen:C1852581,OMIM:12120...","Seizures, benign familial neonatal, 2",germline,germline,GRCh37,NC_000008.10,8,133142159,133142159,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852115,133142159,A,G,-,-,-,-,-,-,SCV007579320,-,-
8982608,4963060,single nucleotide variant,KCNQ3:c.1969T>C p.Tyr657His,3786,KCNQ3,HGNC:6297,Likely benign,0,"Apr 27, 2026",-1,-,RCV006699157,"MONDO:MONDO:0007366,MedGen:C1852581,OMIM:12120...","Seizures, benign familial neonatal, 2",germline,germline,GRCh38,NC_000008.11,8,132129912,132129912,na,na,-,"criteria provided, single submitter",1,-,N,-,2,4852115,132129912,A,G,-,-,-,-,-,-,SCV007579320,-,-